services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'

  mongodb:
    image: mongo:8.0-rc
  redis:
    image: redis:alpine
  mongo-express:
    image: mongo-express:1.0-20-alpine3.19