version: '3.8'

services:
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017
      - REDIS_URI=redis://redis
      - ENABLE_WRITING_HANDLERS=false
    networks:
      - app_network
      - db_network
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:8.0-rc
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - db_network
      - admin_network

  redis:
    image: redis:alpine
    networks:
      - app_network

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - admin_network
    depends_on:
      - mongodb

  mongo-seed:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/tmdb_movies
    depends_on:
      - mongodb
    command: ["node", "seedDatabase.js"]
    networks:
      - db_network

networks:
  app_network:
    driver: bridge
  db_network:
    driver: bridge
  admin_network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
