version: '3.8'

services:
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/tndb_movies
      - REDIS_URI=redis://redis
      - ENABLE_WRITING_HANDLERS=false
    networks:
      - app_network
      - db_network
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:8.0-rc
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - db_network
      - admin_network

  redis:
    image: redis:alpine
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
  db_network:
    driver: bridge
  admin_network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
